name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      # - name: WordPress Plugin SVN Deploy
      #   uses: nk-o/action-wordpress-plugin-deploy@master
      #   env:
      #     SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
      #     SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      #     SLUG: oxyrealm-sandbox
      #     ASSETS_DIR: .wordpress-org

      - name: Clean dev files
        run: rm -rf *.git* node_modules/\* pnpm-lock.yaml composer.lock .wordpress-org .distignore

      - name: Move files to subfolder
        run: mkdir oxyrealm-sandbox && ls && shopt -s extglob && mv ^oxyrealm-sandbox oxyrealm-sandbox

      - name: Create zip
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r "sandbox-${{ steps.get_version.outputs.VERSION }}.zip" .

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload zip to release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sandbox-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: sandbox-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip